### ISSUE TITLE
Specifying timeframe

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [dynatrace-oss/fluent-plugin-dynatrace#26]
I'm ingesting this log line:

```
[2021-09-06 10:00:00 AEST] INFO This is my first log line...
```

I have the following specified in `td-agent.conf`:
```
<source>
  @type tail
  path C:/path/to/your/log/file.log
  pos_file C:/path/to/your/log/file.log.pos
  tag first.*
  <parse>
    @type regexp
	  expression /^\[(?<time>[^\]]+)\] (?<loglevel>[^\s]+) (?<payload>.+)$/
  </parse>
</source>

<match first.**>
  @type              dynatrace
  active_gate_url    https://ACTIVEGATE_IP:9999/e/DT_TENANT_ID/api/v2/logs/ingest
  api_token          ***
  ssl_verify_none    true
</match>
```

I can see the log entries in Dynatrace but the timestamp is always the current time and doesn't reflect the `time` parameter.

Is there a way to configure this?

**Comment by dyladan** [comment]
Hello @Dynatrace-Adam-Gardner. I think you're almost there but you need to use a supported timestamp key like `timestamp`. They are listed in the help docs here: https://www.dynatrace.com/support/help/dynatrace-api/environment-api/log-monitoring-v2/post-ingest-logs/

**Comment by dyladan** [comment]
Hello @Dynatrace-Adam-Gardner. I think you're almost there but you need to use a supported timestamp key like `timestamp`. They are listed in the help docs here: https://www.dynatrace.com/support/help/dynatrace-api/environment-api/log-monitoring-v2/post-ingest-logs/

Updating your config like this should work I think

```
<source>
  @type tail
  path C:/path/to/your/log/file.log
  pos_file C:/path/to/your/log/file.log.pos
  tag first.*
  <parse>
    @type regexp
	  expression /^\[(?<timestamp>[^\]]+)\] (?<loglevel>[^\s]+) (?<payload>.+)$/
  </parse>
</source>

<match first.**>
  @type              dynatrace
  active_gate_url    https://ACTIVEGATE_IP:9999/e/DT_TENANT_ID/api/v2/logs/ingest
  api_token          ***
  ssl_verify_none    true
</match>
```

It is worth pointing out that this is a workaround. The would bypass fluentd's time handling, but Dynatrace would recognize the timestamp because it would be included in the content. This might be an issue if you have non-dynatrace outputs as well.

Another potential solution is to use a filter plugin which inserts the timestamp into the content like this:

```
<source>
  @type tail
  path C:/path/to/your/log/file.log
  pos_file C:/path/to/your/log/file.log.pos
  tag first.*
  <parse>
    @type regexp
	  expression /^\[(?<time>[^\]]+)\] (?<loglevel>[^\s]+) (?<payload>.+)$/
  </parse>
</source>

<filter first.**>
  @type record_transformer
  <record>
    time ${time}
  </record>
</filter>

<match first.**>
  @type              dynatrace
  active_gate_url    https://ACTIVEGATE_IP:9999/e/DT_TENANT_ID/api/v2/logs/ingest
  api_token          ***
  ssl_verify_none    true
</match>

```

**Comment by dyladan** [comment]
Hope this workaround helped. Feel free to reopen this issue if not.

**Comment by dyladan** [comment]
With the 0.1.6 release you can now set the inject_timestamp configuration true to get the timestamp injected into the log message in a format that can be recognized by Dynatrace.
