### ISSUE TITLE
Fluentbit compatibility

### ISSUE THREAD

**Issue by rocky1201** [dynatrace-oss/fluent-plugin-dynatrace#40]
**Is your feature request related to a problem? Please describe.**
Is there a plan to make this plugin compatible with fluentbit? Fluentbit seems to be the successor to fluentd due to its fast and lightweight footprint

**Comment by arminru** [comment]
Hey @rocky1201!
This is already on our roadmap but I can't give you any ETA date for it.
If you'd like to learn more, you could reach out to your Dynatrace representative.
As the implementation for fluentbit will go into the fluentbit repository itself rather than this one here for fluentd, I'll close the issue.
